services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        - spring.datasource.url=jdbc:oracle:thin:@bdbdo_tp?TNS_ADMIN=/app/wallet
        - spring.datasource.username=BD_bdo_SBoot
        - spring.datasource.password=ActForm.S4_DFS
    restart: always